name: CI
on: [push, pull_request]
jobs:
  style:
    name: Style
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Check format
        run: |
          # Make sure to exit with an error if at least one file differs
          git ls-files 'content/*.md' | ( ret=0
            while read -r file
            do
              echo "Checking ${file}"
              diff --color --unified "${file}" <(sed -E 's/[[:blank:]]+$//' "${file}") || ret=$?
            done
            exit ${ret} ) || exit $?
  hugo:
    name: Hugo
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt update || true
          sudo apt --yes --no-install-recommends install hugo
      - name: Configure Pages
        uses: actions/configure-pages@v2
      - name: Build blog
        run: |
          hugo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
  deploy:
    name: Deploy
    needs: hugo
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1
